### ISSUE TITLE
not compatible with java sdk2

### ISSUE THREAD

**Issue by jkuehl2** [awslabs/amazon-sqs-java-extended-client-lib#35]
Is it planned to migrate to aws java sdk2?

**Comment by robin-aws** [comment]
Hi @jkuehl2! We are definitely planning to migrate this library and the other supported SQS libraries to v2 of the Java SDK, but we do not yet have an ETA. v2 changes quite a bit so it will not be entirely trivial.

**Comment by AlexBroadbent** [comment]
Any update on this? I am trying to upgrade from v1 to v2 but am blocked on this library.

**Comment by robin-aws** [comment]
Hi Alex! This is still high on our backlog, and I recently scoped out the v1 to v2 interface changes to estimate how much work it will be (for this library as well as the other customer SQS clients). As expected it's not trivial since all the interfaces changed quite a bit. I'll add your +1 for this library internally and push for getting the resources assigned.

**Comment by kito99** [comment]
@robin-aws any updates? I wonder if we should just manually put the data in an S3 bucket and have a reference to it in our message

**Comment by jimhooker2002** [comment]
Piling on here :-) one more person blocked here, we really want to get onto SDK V2, but this blocks us doing that.
